db.restaurant.find().pretty()
db.restaurant.find({},{_id:0, restaurant_id:1, borough:1, cuisine:1})
db.restaurant.find({},{restaurant_id:1, borough:1, cuisine:1})
db.restaurant.find({},{_id:0, restaurant_id:1, borough:1, address:{zipcode:1}})
db.restaurant.find({borough:"Bronx"}).pretty()
db.restaurant.find({borough:"Bronx"}).limit(5).pretty()
db.restaurant.find({borough:"Bronx"}).skip(5).limit(5).pretty()
db.restaurant.find({"grades.score":{$gt:90}}).pretty()
db.restaurant.find({grades :{$elemMatch:{score:{$gt:80, $lt:100}}}}).pretty()
db.restaurant.find({"address.coord.0":{$gt: -95.754168}}).pretty()
db.restaurant.find({"address.coord.0":{$gt: -65.754168}, "cuisine":{$ne:"American "},"grades.score":{$gt:70} }).pretty()
db.restaurant.find({"address.coord.1":{$gt: -65.754168}, "cuisine":{$ne:"American "},"grades.score":{$gt:70} }).pretty()
db.restaurant.find({"borough":{$ne:"Brooklyn"}, "cuisine":{$ne:"American "},"grades.grade":"A"}).sort({"cuisine":-1}).pretty()
db.restaurant.find({name:/^Wil/},{_id:0, restaurant_id:1, name:1, borough:1, cuisine:1}).pretty()
db.restaurant.find({name:/ces$/},{_id:0, restaurant_id:1, name:1, borough:1, cuisine:1}).pretty()
db.restaurant.find({name:/Reg/},{_id:0, restaurant_id:1, name:1, borough:1, cuisine:1}).pretty()
